# railway.yml

# Specify the version of the Railway CLI
version: '2'

# Define tasks and services
tasks:
  - name: build
    command: go build cmd/main.go

  - name: start
    command: go run cmd/main.go

services:
  - name: redis
    image: redis

  - name: mongodb
    image: mongo
    # Add environment variables for MongoDB configuration (e.g., MONGO_INITDB_ROOT_USERNAME, MONGO_INITDB_ROOT_PASSWORD, MONGO_INITDB_DATABASE)

# Configure environment variables for your Go application
env:
  - key: REDIS_URL
    value: redis://redis:6379  # Use the name of the Redis service as the hostname
  - key: MONGODB_URI
    value: mongodb://mongodb:27017  # Use the name of the MongoDB service as the hostname

# Specify the Dockerfile to use
buildCommand: go build -o ./cmd/myapp ./cmd/main.go
